runtime: nodejs20
service: user

automatic_scaling:
  min_instances: 0
  max_instances: 2
  target_cpu_utilization: 0.65

health_check:
  enable_health_check: True
  check_interval_sec: 5
  timeout_sec: 4
  unhealthy_threshold: 2
  healthy_threshold: 2